name: Simple ML CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run training
      working-directory: .
      run: |
        python app/train.py

    - name: Run prediction
      working-directory: .
      run: |
        python app/predict.py
    
    - name: Run tuning
      working-directory: .
      run: |
        python app/tune.py

    - name: Build Docker image
      working-directory: .
      run: |
        docker build -t simple-ml-app .